### Create Payment
POST http://localhost:8081/payment
Content-Type: application/json

{
  "amount": 100.5,
  "method": "credit_card",
  "status": "pending",
  "created": "2025-04-26T07:30:00Z"
}

### Get Payment Status
GET http://localhost:8081/payment/{paymentId}

### Retry Payment
POST http://localhost:8081/payment/retry/{paymentId}
Content-Type: application/json

{
  "amount": 100.5,
  "method": "credit_card",
  "status": "retrying",
  "created": "2025-04-26T07:30:00Z"
}
